id: cytof_benchmmark_exercise
description: Benchmark of different clustering algorithms for benchmark phd course.
version: 0.3
benchmarker: Andrea Sonnenholzner, Frederik Kirk, Helene Wegener, Javier Herranz
storage: http://omnibenchmark.org:9000
benchmark_yaml_spec: 0.04
storage_api: S3
storage_bucket_name: clusteringexampleconda
software_backend: conda
software_environments:
  py:
    description: clustbench on py3.12.6
    conda: envs/py.yml
    envmodule: py
  py-old:
    description: clustbench on py3.12.6
    conda: envs/py-old.yml
    envmodule: py-old
  cran:
    description: CRAN R environment
    conda: envs/cran.yml
    envmodule: cran
  cran-hw:
    description: CRAN-hw R environment
    conda: envs/cran-hw.yml
    envmodule: cran-hw
  cyanno:
    description: CyAnno module environment
    conda: envs/cyanno_env.yml
    envmodule: cyanno
  gatemeclass:
    description: gatemeclass module environment
    conda: envs/gateme_env.yml
    envmodule: gatemeclass
  dgcytof:
    description: DG-CyTOF legacy environment
    conda: envs/dgcytof.yml
    envmodule: dgcytof
  deepcytof:
    description: Deepcytof environment
    conda: envs/deepcytof.yml
    envmodule: deepcytof
  bash:
    description: Bash environment
    conda: envs/bash.yml
    envmodule: bash
  metrics_r:
    description: Metrics collector R environment
    conda: envs/metrics_r.yml
    envmodule: metrics_r
metric_collectors:
- id: metrics_report
  name: Metrics report collector
  software_environment: metrics_r
  repository:
    url: https://github.com/kaae-2/ob-metrics-collectors.git
    commit: e54a4df6bf5ced0b650cdb7666ecb6cd31c98568
  inputs:
  - metrics.scores
  - data.order
  outputs:
  - id: metrics.report
    path: '{input}/metric_collectors/metrics_report/metrics_report.html'
  - id: metrics.plots
    path: '{input}/metric_collectors/metrics_report/metric_plots.tar.gz'
stages:
- id: data
  modules:
  - id: data_import
    name: Prepared CyTOF CSV dataset from GitHub prepared folder
    software_environment: py
    repository:
      url: https://github.com/kaae-2/ob-pipeline-data
      commit: 6c77d6939ca4297341da4101bf44463ca9c06ecd
    parameters:
    - values:
      - --dataset_name
      - FR-FCM-Z2KP-healthy
      - --seed
      - '42'
      - --transformation-cofactor
      - '150'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FR-FCM-Z2KP-covid
      - --seed
      - '42'
      - --transformation-cofactor
      - '150'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FR-FCM-Z238
      - --seed
      - '42'
      - --transformation-cofactor
      - '5'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FR-FCM-Z3YR
      - --seed
      - '42'
      - --transformation-cofactor
      - '5'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - Samusik
      - --seed
      - '42'
      - --transformation-cofactor
      - '5'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - BodenmillerXL
      - --seed
      - '42'
      - --transformation-cofactor
      - '5'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - Levine
      - --seed
      - '42'
      - --transformation-cofactor
      - '5'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FlowCyt
      - --seed
      - '42'
      - --transformation-cofactor
      - '150'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FR-FCM-Z2KP-healthy
      - --seed
      - '420'
      - --sub-sampling
      - '1000'
      - --transformation-cofactor
      - '150'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FR-FCM-Z2KP-healthy
      - --seed
      - '420'
      - --sub-sampling
      - '5000'
      - --transformation-cofactor
      - '150'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FR-FCM-Z2KP-healthy
      - --seed
      - '420'
      - --sub-sampling
      - '10000'
      - --transformation-cofactor
      - '150'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FR-FCM-Z2KP-healthy
      - --seed
      - '420'
      - --sub-sampling
      - '50000'
      - --transformation-cofactor
      - '150'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
    - values:
      - --dataset_name
      - FR-FCM-Z2KP-healthy
      - --seed
      - '420'
      - --sub-sampling
      - '100000'
      - --transformation-cofactor
      - '150'
      - --potential-batches
      - '1'
      - --name
      - data_import.data_raw
  outputs:
  - id: data.raw
    path: '{input}/{stage}/{module}/{params}/data_raw.data.tar.gz'
  - id: data.order
    path: '{input}/{stage}/{module}/{params}/data_raw.order.json.gz'
- id: preprocessing
  modules:
  - id: data_preprocessing
    name: Data preprocessing for CyTOF datasets
    software_environment: py
    repository:
      url: https://github.com/kaae-2/ob-pipeline-preprocessing
      commit: 0e6c931555e053ab5c42440345bf58b0f6b08358
    parameters:
    - values:
      - --num
      - '1'
      - --max-workers
      - '8'
      - --name
      - data_import.data_preprocessing
    - values:
      - --num
      - '2'
      - --max-workers
      - '8'
      - --name
      - data_import.data_preprocessing
    - values:
      - --num
      - '3'
      - --max-workers
      - '8'
      - --name
      - data_import.data_preprocessing
    - values:
      - --num
      - '4'
      - --max-workers
      - '8'
      - --name
      - data_import.data_preprocessing
    - values:
      - --num
      - '5'
      - --max-workers
      - '8'
      - --name
      - data_import.data_preprocessing
  inputs:
  - entries:
    - data.raw
    - data.order
  outputs:
  - id: data.train_matrix
    path: '{input}/{stage}/{module}/{params}/data_preprocessing.train.matrix.tar.gz'
  - id: data.train_labels
    path: '{input}/{stage}/{module}/{params}/data_preprocessing.train.labels.tar.gz'
  - id: data.test_matrix
    path: '{input}/{stage}/{module}/{params}/data_preprocessing.test.matrices.tar.gz'
  - id: data.true_labels
    path: '{input}/{stage}/{module}/{params}/data_preprocessing.test.labels.tar.gz'
  - id: data.label_key
    path: '{input}/{stage}/{module}/{params}/data_preprocessing.label_key.json.gz'
- id: stratify
  modules:
  - id: data_stratify
    name: Stratify preprocessed CyTOF datasets
    software_environment: py
    repository:
      url: https://github.com/kaae-2/ob-stratify.git
      commit: 58d322e459c1308673325cf7e669ce2ca329a20a
    parameters:
    - values:
      - --drop-ungated-training
      - 'false'
      - --drop-ungated-test
      - 'false'
    - values:
      - --drop-ungated-training
      - 'false'
      - --drop-ungated-test
      - 'true'
    - values:
      - --drop-ungated-training
      - 'true'
      - --drop-ungated-test
      - 'true'
  inputs:
  - entries:
    - data.train_matrix
    - data.train_labels
    - data.test_matrix
    - data.true_labels
    - data.label_key
    - data.order
  outputs:
  - id: data.post_stratify_train_matrix
    path: '{input}/{stage}/{module}/{params}/{dataset}.train.matrix.tar.gz'
  - id: data.post_stratify_train_labels
    path: '{input}/{stage}/{module}/{params}/{dataset}.train.labels.tar.gz'
  - id: data.post_stratify_test_matrix
    path: '{input}/{stage}/{module}/{params}/{dataset}.test.matrices.tar.gz'
  - id: data.post_stratify_true_labels
    path: '{input}/{stage}/{module}/{params}/{dataset}.test.labels.tar.gz'
  - id: data.post_stratify_label_key
    path: '{input}/{stage}/{module}/{params}/{dataset}.label_key.json.gz'
  - id: data.post_stratify_order
    path: '{input}/{stage}/{module}/{params}/{dataset}.order.json.gz'
- id: analysis
  inputs:
  - entries:
    - data.post_stratify_train_matrix
    - data.post_stratify_train_labels
    - data.post_stratify_test_matrix
    - data.post_stratify_label_key
  modules:
  - id: dgcytof
    name: DG-CyTOF
    software_environment: py
    repository:
      url: https://github.com/kaae-2/ob-pipeline-dgcytof
      commit: caba3a4b82e9e9c71354ab53f3d9050a052ddfbf
    parameters: []
  - id: cygate
    name: CyGATE
    software_environment: bash
    repository:
      url: https://github.com/kaae-2/ob-pipeline-CyGATE
      commit: 673e7292da363a8b3e53cc57b6c739e5e321adc9
  - id: random
    name: Random
    software_environment: cran
    repository:
      url: https://github.com/kaae-2/ob-pipeline-random
      commit: 134261352ff751c2995a29e43d3a6fb2a983f668
    parameters: []
  - id: cyanno
    name: CyAnno
    software_environment: cyanno
    repository:
      url: https://github.com/kaae-2/ob-pipeline-cyanno
      commit: 0c3610615b832012518ec48a9ec513619d0dab67
    parameters: []
  - id: knn
    name: KNN
    software_environment: py
    repository:
      url: https://github.com/kaae-2/ob-pipeline-knn
      commit: 24d7e1d0960aa860bec8e1acca6b286894528926
    parameters: []
  - id: lda
    name: LDA
    software_environment: cran
    repository:
      url: https://github.com/kaae-2/ob-pipeline-LDA
      commit: 120175fcb280263c71e5d91c27658073c2d96c28
    parameters: []
  - id: gatemeclass
    name: GateMeClass
    software_environment: gatemeclass
    repository:
      url: https://github.com/kaae-2/GateMeClass_model
      commit: fc605c556f1f034559cce90f2bcdbb82d35427f0
    parameters:
    - values:
      - --GMM_parameterization
      - E
      - --sampling
      - '0.1'
      - --k
      - '20'
      - --excluded-datasets
      - FR-FCM-Z3YR,FlowCyt,FR-FCM-Z2KP-covid,FR-FCM-Z238
    - values:
      - --GMM_parameterization
      - V
      - --sampling
      - '0.1'
      - --k
      - '20'
      - --excluded-datasets
      - FR-FCM-Z3YR,FlowCyt,FR-FCM-Z2KP-covid,FR-FCM-Z238
  outputs:
  - id: analysis.prediction
    path: '{input}/{stage}/{module}/{params}/{dataset}_predicted_labels.tar.gz'
- id: metrics
  modules:
  - id: flow_metrics
    name: benchmark metrics for flow/cytof data
    software_environment: py
    repository:
      url: https://github.com/kaae-2/ob-pipeline-metrics
      commit: 4e58b8b03ff22d5477ae1099e792fe657ee296ca
    parameters: []
  inputs:
  - entries:
    - analysis.prediction
    - data.post_stratify_true_labels
    - data.post_stratify_label_key
    - data.post_stratify_order
  outputs:
  - id: metrics.scores
    path: '{input}/{stage}/{module}/{params}/{dataset}.flow_metrics.json.gz'
